spring:
  datasource:
    url: jdbc:p6spy:sqlserver://localhost:1433;databaseName=QuanLyHocTap;encrypt=false
    username: sa
    password: 1234
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd
    serialization:
      write-dates-as-timestamps: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  time-zone: Asia/Ho_Chi_Minh
logging:
  level:
    p6spy: DEBUG

jwt:
  secretKey: "a1Y1ksRv71WUdnPa6RNwqoc4Y5xtab+iHDrknQJjvlk="
